//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amenaza()
        {
            this.ListadoRiesgo = new HashSet<ListadoRiesgo>();
        }
    
        public int idAmenaza { get; set; }
        public string origen { get; set; }
        public string nombre { get; set; }
        public double probabilidad { get; set; }
        public double impacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadoRiesgo> ListadoRiesgo { get; set; }
    }
}
