//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAid
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoRiesgo
    {
        public int idListadoRiesgo { get; set; }
        public string codigoActivo { get; set; }
        public Nullable<int> idVulnerabilidad { get; set; }
        public Nullable<int> idAmenaza { get; set; }
        public Nullable<int> idControl { get; set; }
        public Nullable<double> riesgo { get; set; }
    
        public virtual Amenaza Amenaza { get; set; }
        public virtual Controles Controles { get; set; }
        public virtual ListadoActivos ListadoActivos { get; set; }
        public virtual Vulnerabilidad Vulnerabilidad { get; set; }
    }
}
