//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAid
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoActivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListadoActivos()
        {
            this.ListadoRiesgo = new HashSet<ListadoRiesgo>();
        }
    
        public string codigoActivo { get; set; }
        public string nombreActivo { get; set; }
        public string descripcionActivo { get; set; }
        public string propietario { get; set; }
        public string protector { get; set; }
        public Nullable<int> tipoActivo { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> integridad { get; set; }
        public Nullable<int> disponibilidad { get; set; }
        public Nullable<int> confidencialidad { get; set; }
        public string justificacion { get; set; }
        public Nullable<double> valoracion { get; set; }
    
        public virtual AreaActivo AreaActivo { get; set; }
        public virtual Confidencialidad Confidencialidad1 { get; set; }
        public virtual Disponibilidad Disponibilidad1 { get; set; }
        public virtual Integridad Integridad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadoRiesgo> ListadoRiesgo { get; set; }
        public virtual TipoActivo TipoActivo1 { get; set; }
    }
}
