//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValoracionActivosEntities : DbContext
    {
        public ValoracionActivosEntities()
            : base("name=ValoracionActivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenaza> Amenaza { get; set; }
        public virtual DbSet<AreaActivo> AreaActivo { get; set; }
        public virtual DbSet<Confidencialidad> Confidencialidad { get; set; }
        public virtual DbSet<Controles> Controles { get; set; }
        public virtual DbSet<Disponibilidad> Disponibilidad { get; set; }
        public virtual DbSet<Integridad> Integridad { get; set; }
        public virtual DbSet<ListadoActivos> ListadoActivos { get; set; }
        public virtual DbSet<ListadoRiesgo> ListadoRiesgo { get; set; }
        public virtual DbSet<TipoActivo> TipoActivo { get; set; }
        public virtual DbSet<Vulnerabilidad> Vulnerabilidad { get; set; }
    }
}
